### ISSUE TITLE
`GateWithRegisters.controlled` does not work with call graph

### ISSUE THREAD

**Issue by anurudhp** [quantumlib/Qualtran#865] opened 2024-04-09 21:05 UTC
https://github.com/quantumlib/Qualtran/pull/848#discussion_r1558277485

Replacing `Controlled(self.U, CtrlSpec(cvs=0))` with `self.U.controlled(control_values=[0])` in GQSP results in:

```
AttributeError: 'BloqAsCirqGate' object has no attribute 'pretty_name'
```

Minimal code to reproduce error:
```py
from qualtran.bloqs.basic_gates import XPowGate
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from qualtran.drawing import show_call_graph

gqsp = GeneralizedQSP.from_qsp_polynomial(XPowGate(), (0.5, 0.5))
g, _ = gqsp.call_graph(max_depth=1)
show_call_graph(g)
```

**Comment by mpharrigan** [comment] 2024-04-15 21:18
I can't reproduce this on `main`. There was a recent PR merged that moved `controlled` to the bloqs one; maybe @tanujkhattar knows more

**Comment by anurudhp** [comment] 2024-04-15 23:57
It still crashes for me on main, on replacing
https://github.com/quantumlib/Qualtran/blob/43e3032f0f35b427b3bde984d39a2a7cb749974b/qualtran/bloqs/qsp/generalized_qsp.py#L404
with
```py
counts.add((self.U.controlled(control_values=[0]), degree - self.negative_power))
```
(in `build_call_graph`)

**Closed** 2024-04-19 00:20 UTC
