### ISSUE TITLE
Soquet finalization error when decomposing from cirq style method

### ISSUE THREAD

**Issue by kjm538** [quantumlib/Qualtran#1118] opened 2024-07-09 21:08 UTC
I am encountering the error 
```python-traceback 
BloqError: During finalization, {Soquet(binst=LeftDangle, reg=Register(name='z', dtype=QAny(bitsize=6), _shape=(), side=<Side.THRU: 3>), idx=())} Soquets were not used.
```
when decomposing some of my custom GateWithRegister objects. As a simple example, consider the following gate

```Python
from qualtran import Signature, GateWithRegisters
from qualtran.bloqs.arithmetic import OutOfPlaceAdder
from functools import cached_property

class myGate(GateWithRegisters):

    @cached_property
    def signature(self) -> Signature:
        return Signature.build(x=5,y=5,z=6)

    def decompose_from_registers(self,
        *,
        context: cirq.DecompositionContext,
        **quregs,
    ) -> cirq.OP_TREE:

        xreg = quregs['x']
        yreg = quregs['y']
        zreg = quregs['z']

        yield OutOfPlaceAdder(bitsize=5).on_registers(a=xreg,b=yreg,c=zreg)
```
Trying to decompose results in the following:
```python-traceback
---------------------------------------------------------------------------
BloqError                                 Traceback (most recent call last)
Cell In[53], line 1
----> 1 myGate().decompose_bloq()

File ~/.../site-packages/qualtran/_infra/gate_with_registers.py:293, in GateWithRegisters.decompose_bloq(self)
    291     return Bloq.decompose_bloq(self)
    292 except DecomposeNotImplementedError:
--> 293     return decompose_from_cirq_style_method(self)

File ~/.../site-packages/qualtran/cirq_interop/_cirq_to_bloq.py:613, in decompose_from_cirq_style_method(bloq, method_name)
    611     raise DecomposeNotImplementedError(str(exc)) from exc
    612 else:
--> 613     raise exc

File ~/.../site-packages/qualtran/cirq_interop/_cirq_to_bloq.py:606, in decompose_from_cirq_style_method(bloq, method_name)
    604 decomposed_optree = dfr_method(context=context, **all_quregs)
    605 try:
--> 606     return cirq_optree_to_cbloq(
    607         decomposed_optree, signature=bloq.signature, in_quregs=in_quregs, out_quregs=out_quregs
    608     )
    609 except ValueError as exc:
    610     if "Only gate operations are supported" in str(exc):

File ~/.../site-packages/qualtran/cirq_interop/_cirq_to_bloq.py:565, in cirq_optree_to_cbloq(optree, signature, in_quregs, out_quregs)
    563     if qvar not in final_soqs_set:
    564         bb.free(qvar)
--> 565 return bb.finalize(**final_soqs_dict)

File ~/.../site-packages/qualtran/_infra/composite_bloq.py:1073, in BloqBuilder.finalize(self, **final_soqs)
   1057 \"\"\"Finish building a CompositeBloq and return the immutable CompositeBloq.
   1058 
   1059 This method is similar to calling `add()` but instead of adding a new Bloq,
   (...)
   1070         final`Soquet`s, e.g. the output soquets from a prior, final operation.
   1071 \"\"\"
   1072 if not self.add_register_allowed:
-> 1073     return self._finalize_strict(**final_soqs)
   1075 # If items from `final_soqs` don't already exist in `_regs`, add RIGHT registers
   1076 # for them. Then call `_finalize_strict` where the actual dangling connections are added.
   1078 def _infer_reg(name: str, soq: SoquetT) -> Register:

File ~/.../site-packages/qualtran/_infra/composite_bloq.py:1114, in BloqBuilder._finalize_strict(self, **final_soqs)
   1110 _process_soquets(
   1111     registers=signature.rights(), debug_str='Finalizing', in_soqs=final_soqs, func=_fin
   1112 )
   1113 if self._available:
-> 1114     raise BloqError(
   1115         f\"During finalization, {self._available} Soquets were not used.\"
   1116     ) from None
   1118 return CompositeBloq(
   1119     connections=self._cxns, signature=signature, bloq_instances=self._binsts
   1120 )

BloqError: During finalization, {Soquet(binst=LeftDangle, reg=Register(name='z', dtype=QAny(bitsize=6), _shape=(), side=<Side.THRU: 3>), idx=())} Soquets were not used.
```
Of course my gate decompositions are composed of several gates, not just the adder. Additionally, I don't think this error is isolated to the OutOfPlaceAdder, since some of my gates don't use this but I still get a similar BloqError. I don't understand why this error is coming up since the z register is definitely used in the decomposition.

**Comment by anurudhp** [comment] 2024-07-14 06:53
In `OutOfPlaceAdder`, `c` is a RIGHT register: https://github.com/quantumlib/Qualtran/blob/f8cebdb50500fe1fe288da35ce504fe81a58a12d/qualtran/bloqs/arithmetic/addition.py#L267-L275

But in your code, `z` is declared as a THRU register, so the input `z` is not being used (the error above). As cirq doesn't support LEFT/RIGHT registers, the cirq-interop just allocates the non-THRU qubits and passes them to the cirq style decompose, which is causing this issue. One fix in the above case is to declare `z` as a RIGHT register.

@tanujkhattar thoughts?

**Comment by tanujkhattar** [comment] 2024-07-15 16:32
@kjm538  The explanation given by Anurudh above is correct. 

All Bloq's have registers that can have sides. A THRU register means the bloq acts on a set of qubits (represented by that register) which are already allocated and remain allocated in the same shape and type. When one builds a signature via `Signature.build()` or `Signature.build_from_dtypes`, the default `side` is `Side.THRU`. However, bloqs can also have `LEFT` and `RIGHT` registers. A `LEFT` register represents a wire that comes in but doesn't go out -- this represents a deallocation of the underlying register. A `RIGHT` register represents a wire that only comes out -- this represents  a qubit allocation. 

When using the `decompose_bloq()` API to write a decomposition, there are automated checks to verify that all wires are connected correctly. Using a `BloqBuilder`, when a user calls `output_soqs = bb.add(bloq, input_soqs)` the number of input soquets (equivalent of qubits / list of qubits in Cirq) can be different from the number of output Soquets. Therefore, when you would add an `OutOfPlaceAdder` bloq via the bloq builder API, you would write `xreg, yreg, zreg = bb.add(OutOfPlaceAdder(5), a=xreg, b=yreg)` : Notice how in inputs you've only specified two soquets for `a, b` and the output has 3 soquets for `a, b, c` because `c` is a `RIGHT` register. 

When using the cirq-style API, we have a restriction that number of inputs must be equal to the number of outputs. This comes from the fundamental design of Cirq. Therefore, to support sided registers, we have an assumption that whenever a bloq expects a LEFT / RIGHT register, the bloq author takes care of the allocation / deallocation of that register. In this case, one needs to make sure that the `c` input passed to the the  `OutOfPlaceAdder(5).on_registers()` call corresponds to a newly allocated register. This can be done either by declaring `z` as a `RIGHT` register, in which case this requirement is further pushed up the stack and so you can assume that `myBloq` receives a newly allocated register for `z` and simply passes it to `OutOfPlaceAdder`. Or, you could declare a newly allocated register via `context.qm.qalloc(5)` and pass this to `OutOfPlacerAdder`. These would be different decompositions depending on the context (eg: if you want to add two numbers, consume the result, and then undo the operation as part of the decomposition). 


The following works. 

```python
In [9]: from qualtran import Signature, Register, Side, QUInt, GateWithRegisters
   ...: from qualtran.bloqs.arithmetic import OutOfPlaceAdder
   ...: from functools import cached_property
   ...:
   ...: class myGate(GateWithRegisters):
   ...:
   ...:     @cached_property
   ...:     def signature(self) -> Signature:
   ...:         return Signature([Register('x', QUInt(5)), Register('y', QUInt(5)), Register('z', QUInt(6), side=Side.RIGHT)])
   ...:
   ...:     def decompose_from_registers(self,
   ...:         *,
   ...:         context: cirq.DecompositionContext,
   ...:         **quregs,
   ...:     ) -> cirq.OP_TREE:
   ...:         xreg = quregs['x']
   ...:         yreg = quregs['y']
   ...:         zreg = quregs['z']
   ...:         yield OutOfPlaceAdder(bitsize=5).on_registers(a=xreg,b=yreg,c=zreg)
```


Hope the explanation helps. Let us know if you have any more questions. I'll close the issue with working as intended.

**Closed by tanujkhattar** 2024-07-15 16:32 UTC
